url: http://www.lezotte.net
baseurl: /

# Site settings
title: LeZotte
email: tom@lezotte.net
description: ""

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url:
  - title: linkedin
    url:
  - title: stack-overflow
    url:
  - title: github
    url:

# Build settings
markdown: kramdown
permalink: pretty
